## One pair of brackets []

# In Pandas, df[...] means “select something from the DataFrame.”

# Whatever you put inside the brackets tells Pandas what to select (rows or columns).

## Inside the brackets, another pair of brackets ["Name", "Math", "English"]

# Here, you are passing a list of column names.

## A list in Python is written with square brackets: ["Name", "Math", "English"].

# This list says: “I want the columns Name, Math, and English.”

# Putting them together

# The outer brackets tell Pandas: “select columns.”

# The inner brackets are just Python syntax for a list of column names.

## A DataFrame is like a spreadsheet or table inside Python. It organizes data into rows and columns, making it easy to clean, analyze, and visualize.

--------------------1. data["Math"] >= 85
This checks each student’s Math score.

If the score is greater than or equal to 85, it returns True.

Otherwise, it returns False.

 Example:

Alice (Math = 85) → True

Bob (Math = 90) → True

Ethan (Math = 70) → False

So you get a list of True/False values for the whole column.

2. data[data["Math"] >= 85]
This is Pandas’ way of filtering rows.

It keeps only the rows where the condition is True.

In this case, it keeps only students with Math ≥ 85.

The result is stored in high_math.

 Meaning: high_math is a smaller DataFrame showing only the top Math students.

3. data[data["Average"] >= 80]
Same idea, but now the condition is on the Average column.

It keeps only students whose average score is ≥ 80.

The result is stored in strong_students.

 Meaning: strong_students is a smaller DataFrame showing only students with strong overall performance.

4. print(high_math) and print(strong_students)
These lines display the filtered DataFrames.

You’ll see only the rows that meet the conditions.

Key Differences
Aspect	Data Analysis 🧮	                      Machine Learning 🤖
Purpose	Understand past & present	              Predict future outcomes
Questions	“What happened?”	                  “What will happen?”
Techniques	Cleaning, grouping, visualization	  Training models, prediction
Libraries	pandas, numpy, seaborn	              scikit-learn, tensorflow
Output	Insights, charts, summaries	              Predictions, classifications


Data Analysis = looking backward and present → understanding data.

Machine Learning = looking forward → predicting outcomes from data.

Import Libraries
python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
NumPy → numerical operations.

Pandas → data handling (loading CSV, slicing columns).

Matplotlib → plotting (not used yet, but imported for visualization).

#### Step 2: Load the Dataset
python
dataset = pd.read_csv('data_c.csv')
X = dataset.iloc[:, :-1].values   # all columns except last → independent variables
y = dataset.iloc[:, -1].values    # last column → dependent variable
X = features (country, age, salary).

y = target (Yes/No).

.iloc[:, :-1] means “all rows, all columns except the last.”

.iloc[:, -1] means “all rows, only the last column.”

#### Step 3: Print Raw Data
python
print(X)
Shows:

Code
[['Poland' 54.0 82000.0]
 ['Germany' 37.0 58000.0]
 ...
 ['United States' 50.0 nan]   # missing salary
 ['Germany' nan 62000.0]      # missing age
]
## Notice the missing values (nan).

python
print(y)
['No' 'Yes' 'No' 'No' 'Yes' ...]
## Target variable is categorical (Yes/No).

#### Step 4: Handle Missing Data
python
from sklearn.impute import SimpleImputer
s = SimpleImputer(missing_values=pd.NA, strategy='mean')
imputer = s.fit(X[:, 1:3])          # select numeric columns (age, salary)
X[:, 1:3] = imputer.fit_transform(X[:, 1:3])
SimpleImputer replaces missing values.

strategy='mean' → missing values replaced with the average of that column.

Example: missing salary replaced with mean salary (≈ 73777.77).

Missing age replaced with mean age (≈ 48.77).

## After this, no more nan.

#### Step 5: Encode Categorical Independent Variable
python
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing i mport OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = ct.fit_transform(X)
Column 0 (Country) is categorical (Poland, Germany, United States).

OneHotEncoder converts categories into binary columns:

Poland → [0,1,0]

Germany → [1,0,0]

United States → [0,0,1]

remainder='passthrough' keeps the other numeric columns (age, salary).

#### Now X is fully numeric:

Code
[[0.0 1.0 0.0 54.0 82000.0]
 [1.0 0.0 0.0 37.0 58000.0]
 [0.0 0.0 1.0 40.0 64000.0]
 ...
]
#### Step 6: Encode Dependent Variable
python
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)
Target variable y was categorical (Yes/No).

LabelEncoder converts it to numeric:

No → 0

Yes → 1

#### Final y:

Code
[0 1 0 0 1 1 0 1 0 1]